<!DOCTYPE html>
<!--[if IE]><![endif]-->
<html>
  
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Best practices for exceptions | CoreCLR site</title>
    <meta name="viewport" content="width=device-width">
    <meta name="title" content="Best practices for exceptions | CoreCLR site">
    
    <link rel="shortcut icon" href="../../../images/Logo_DotNet.png" type="image/x-icon">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="../../../styles/docfx.vendor.css">
    <link rel="stylesheet" href="../../../styles/main.css">
    <link rel="stylesheet" href="../../../styles/docfx.css">
    <link rel="stylesheet" href="../../../styles/style.css">
    <meta property="docfx:navrel" content="../../../toc.html">
    <meta property="docfx:tocrel" content="">
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  
    ga('create', 'UA-63735192-1', 'auto');
    ga('send', 'pageview');
    </script>
  </head>  <body data-spy="scroll" data-target="#affix">
    <div id="wrapper">
      <header>
        
        <nav class="navbar navbar-inverse">
             <div class="container">
               <a href="../../../"><img height="50px" src="../../../images/Logo_DotNet.png" style="float:right;"></a>
               <div class="navbar-header ">
                 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                   <span class="sr-only">Toggle navigation</span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                   <span class="icon-bar"></span>
                 </button>
                 <a class="navbar-brand" href="../../../"><span class="dotnet">.NET Core</span></a>
               </div>
               <div id="navbar" class="collapse navbar-collapse">
               </div><!--/.nav-collapse -->
             </div>
           </nav>
        
        <div class="subnav navbar navbar-default">
          <div class="container hide-when-search" id="breadcrumb">
            <ul class="breadcrumb">
              <li></li>
            </ul>
          </div>
        </div>
      </header>
      <div role="main" class="container body-content">
        <div class="article row grid">
          <div class="col-md-10">
            <article class="content wrap" id="_content">
              <a href="https://github.com/dotnet/core-docs/blob/master/docs/essentials/exceptions/exceptions-best-practices.md/#L1" class="pull-right mobile-hide"><span class="fa fa-github"></span> Improve this Doc</a>
              <h1 id="best-practices-for-exceptions">Best practices for exceptions</h1>
              
<p>A well-designed app handles exceptions and errors to prevent app crashes. This article describes best practices for handling and creating exceptions.</p>
<h2 id="handle-exceptions">Handle exceptions</h2>
<p>The following list contains some general guidelines for handling exceptions in your app.</p>
<ul>
<li><p>Use exception handling code (<strong>try</strong>/<strong>catch</strong> blocks) appropriately. You can also programmatically check for a condition that is likely to occur without using exception handling.</p>
<p><strong>Programmatic checks</strong>. The following example uses an <strong>if</strong> statement to check whether a connection is closed. If it isn&#39;t, the example closes the connection instead of throwing an exception.</p>
<p>C#</p>
<pre><code>if (conn.State != ConnectionState.Closed)
{
    conn.Close();
}
</code></pre><p>C++</p>
<pre><code>if (conn-&gt;State != ConnectionState::Closed)
{
    conn-&gt;Close();
}
</code></pre><p>Visual Basic</p>
<pre><code>If conn.State &lt;&gt; ConnectionState.Closed Then
    conn.Close()
End IF
</code></pre><p><strong>Exception handling</strong>. The following example uses a <strong>try</strong>/<strong>catch</strong> block to check the connection and to throw an exception if the connection is not closed.</p>
<p>C#</p>
<pre><code>Try
conn.Close()
Catch ex As InvalidOperationException
Console.WriteLine(ex.GetType().FullName)
Console.WriteLine(ex.Message)
End Try
</code></pre><p>C++</p>
<pre><code>try
{
conn-&gt;Close();
}
catch (InvalidOperationException^ ex)
{
Console::WriteLine(ex-&gt;GetType()-&gt;FullName);
Console::WriteLine(ex-&gt;Message);
}
</code></pre><p>Visual Basic</p>
<pre><code>Try
conn.Close()
Catch ex As InvalidOperationException
Console.WriteLine(ex.GetType().FullName)
Console.WriteLine(ex.Message)
End Try
</code></pre><p>The method you choose depends on how often you expect the event to occur.</p>
<ul>
<li><p>Use exception handling if the event doesn&#39;t occur very often, that is, if the event is truly exceptional and indicates an error (such as an unexpected end-of-file). When you use exception handling, less code is executed in normal conditions.</p>
</li>
<li><p>Use the programmatic method to check for errors if the event happens routinely and could be considered part of normal execution. When you check for errors programmatically, more code is executed if an exception occurs.</p>
</li>
</ul>
</li>
<li><p>Use <strong>try</strong>/<strong>catch</strong> blocks around code that can potentially generate an exception, and use a <strong>finally</strong> block to clean up resources, if necessary. This way, the <strong>try</strong> statement generates the exception, the <strong>catch</strong> statement handles the exception, and the finally statement closes or deallocates resources whether or not an exception occurs.</p>
</li>
<li><p>In <strong>catch</strong> blocks, always order exceptions from the most specific to the least specific. This technique handles the specific exception before it is passed to a more general <strong>catch</strong> block.</p>
</li>
</ul>
<h2 id="creating-and-raising-exceptions">Creating and raising exceptions</h2>
<p>The following list contains guidelines for creating your own exceptions and when they should be raised. For a more details, see <a href="https://msdn.microsoft.com/library/ms229014">Design Guidelines for Exceptions</a>.</p>
<ul>
<li><p>Design classes so that an exception is never thrown in normal use. For example, a <a href="https://msdn.microsoft.com/library/system.io.filestream">FileStream</a> class provides methods that help determine whether the end of the file has been reached. This avoids the exception that is thrown if you read past the end of the file. The following example shows how to read to the end of the file.</p>
<p>C#</p>
<pre><code>class FileRead
{
    public void ReadAll(FileStream fileToRead)
    {
        // This if statement is optional
        // as it is very unlikely that
        // the stream would ever be null.
        if (fileToRead == null)
        {
            throw new System.ArgumentNullException();
        }

        int b;

        // Set the stream position to the beginning of the file.
        fileToRead.Seek(0, SeekOrigin.Begin);

        // Read each byte to the end of the file.
        for (int i = 0; i &lt; fileToRead.Length; i++)
        {
            b = fileToRead.ReadByte();
            Console.Write(b.ToString());
            // Or do something else with the byte.
        }
    }
}
</code></pre><p>C++</p>
<pre><code>class FileRead
{
public:
    void ReadAll(FileStream^ fileToRead)
    {
        // This if statement is optional
        // as it is very unlikely that
        // the stream would ever be null.
        if (fileToRead == nullptr)
        {
            throw gcnew System::ArgumentNullException();
        }

        int b;

        // Set the stream position to the beginning of the file.
        fileToRead-&gt;Seek(0, SeekOrigin::Begin);

        // Read each byte to the end of the file.
        for (int i = 0; i &lt; fileToRead-&gt;Length; i++)
        {
            b = fileToRead-&gt;ReadByte();
            Console::Write(b.ToString());
            // Or do something else with the byte.
        }
    }
};
</code></pre><p>Visual Basic</p>
<pre><code>Class FileRead
    Public Sub ReadAll(fileToRead As FileStream)
        &#39; This if statement is optional
        &#39; as it is very unlikely that
        &#39; the stream would ever be null.
        If fileToRead Is Nothing Then
            Throw New System.ArgumentNullException()
        End If

        Dim b As Integer

        &#39; Set the stream position to the beginning of the file.
        fileToRead.Seek(0, SeekOrigin.Begin)

        &#39; Read each byte to the end of the file.
        For i As Integer = 0 To fileToRead.Length - 1
            b = fileToRead.ReadByte()
            Console.Write(b.ToString())
            &#39; Or do something else with the byte.
        Next i
    End Sub
End Class
</code></pre></li>
<li><p>Throw exceptions instead of returning an error code or HRESULT.</p>
</li>
<li><p>Return null for extremely common error cases instead of throwing an exception. An extremely common error case can be considered normal flow of control. By returning null in these cases, you minimize the performance impact to an app.</p>
</li>
<li><p>In most cases, use the predefined .NET Framework exception types. Introduce a new exception class only when a predefined one doesn&#39;t apply.</p>
</li>
<li><p>Throw an <a href="https://msdn.microsoft.com/library/system.invalidoperationexception">InvalidOperationException</a> exception if a property set or method call is not appropriate given the object&#39;s current state.</p>
</li>
<li><p>Throw an <a href="https://msdn.microsoft.com/library/system.argumentexception">ArgumentException</a> exception or a class derived from <a href="https://msdn.microsoft.com/library/system.argumentexception">ArgumentException</a> if invalid parameters are passed.</p>
</li>
<li><p>For most apps, derive custom exceptions from the <a href="https://msdn.microsoft.com/library/system.exception">Exception</a> class. Deriving from the <a href="https://msdn.microsoft.com/library/system.applicationexception">ApplicationException</a> class doesn&#39;t add significant value.</p>
</li>
<li><p>End exception class names with the word &quot;Exception&quot;. For example:</p>
<p>C#</p>
<pre><code>public class MyFileNotFoundException : Exception
{
}
</code></pre><p>C++</p>
<pre><code>public ref class MyFileNotFoundException : public Exception
{
};
</code></pre><p>Visual Basic</p>
<pre><code>Public Class MyFileNotFoundException
    Inherits Exception
End Class
</code></pre></li>
<li><p>In C# and C++, use at least the three common constructors when creating your own exception classes: the default constructor, a constructor that takes a string message, and a constructor that takes a string message and an inner exception. For an example, see How to: Create User-Defined Exceptions.</p>
<ul>
<li><p><a href="https://msdn.microsoft.com/library/9f9b3wha">Exception()</a>, which uses default values.</p>
</li>
<li><p><a href="https://msdn.microsoft.com/library/48ca3hhw">Exception(String)</a>, which accepts a string message.</p>
</li>
<li><p><a href="https://msdn.microsoft.com/library/804f22sf">Exception(String, Exception)</a>, which accepts a string message and an inner exception.</p>
</li>
</ul>
</li>
<li><p>When you create user-defined exceptions, you must ensure that the metadata for the exceptions is available to code that is executing remotely, including when exceptions occur across app domains. For example, suppose App Domain A creates App Domain B, which executes code that throws an exception. For App Domain A to properly catch and handle the exception, it must be able to find the assembly that contains the exception thrown by App Domain B. If App Domain B throws an exception that is contained in an assembly under its application base, but not under App Domain A&#39;s application base, App Domain A will not be able to find the exception, and the common language runtime will throw a <a href="https://msdn.microsoft.com/library/system.io.filenotfoundexception">FileNotFoundException</a> exception. To avoid this situation, you can deploy the assembly that contains the exception information in two ways:</p>
<ul>
<li><p>Put the assembly into a common application base shared by both app domains.</p>
<p>- or -</p>
</li>
<li><p>If the domains do not share a common application base, sign the assembly that contains the exception information with a strong name and deploy the assembly into the global assembly cache.</p>
</li>
</ul>
</li>
<li><p>Include a localized description string in every exception. The error message that the user sees is derived from the description string of the exception that was thrown, and not from the exception class.</p>
</li>
<li><p>Use grammatically correct error messages, including ending punctuation. Each sentence in a description string of an exception should end in a period. For example, &quot;The log table has overflowed.” would be an appropriate description string.</p>
</li>
<li><p>Provide <a href="https://msdn.microsoft.com/library/system.exception">Exception</a> properties for programmatic access. Provide additional properties for an exception (in addition to the description string) only when there&#39;s a programmatic scenario where the additional information is useful. For example, the <a href="https://msdn.microsoft.com/library/system.io.filenotfoundexception">FileNotFoundException</a> provides the <a href="https://msdn.microsoft.com/library/system.io.filenotfoundexception.filename">FileName</a> property.</p>
</li>
<li><p>The stack trace begins at the statement where the exception is thrown and ends at the <strong>catch</strong> statement that catches the exception. Be aware of this fact when deciding where to place a <strong>throw</strong> statement.</p>
</li>
<li><p>Use exception builder methods. It is common for a class to throw the same exception from different places in its implementation. To avoid excessive code, use helper methods that create the exception and return it. For example:</p>
<p>C#</p>
<pre><code>Class FileReader
    Private fileName As String

    Public Sub New(path As String)
        fileName = path
    End Sub

    Public Function Read(bytes As Integer) As Byte()
        Dim results() As Byte = FileUtils.ReadFromFile(fileName, bytes)
        If results Is Nothing
            Throw NewFileIOException()
        End If
        Return results
    End Function

    Function NewFileIOException() As FileReaderException
        Dim description As String = &quot;My NewFileIOException Description&quot;

        Return New FileReaderException(description)
    End Function
End Class
</code></pre><p>C++</p>
<pre><code>ref class FileReader
{
private:
    String^ fileName;

public:
    FileReader(String^ path)
    {
        fileName = path;
    }

    array&lt;Byte&gt;^ Read(int bytes)
    {
        array&lt;Byte&gt;^ results = FileUtils::ReadFromFile(fileName, bytes);
        if (results == nullptr)
        {
            throw NewFileIOException();
        }
        return results;
    }

    FileReaderException^ NewFileIOException()
    {
        String^ description = &quot;My NewFileIOException Description&quot;;

        return gcnew FileReaderException(description);
    }
};
</code></pre><p>Visual Basic</p>
<pre><code>Class FileReader
    Private fileName As String

    Public Sub New(path As String)
        fileName = path
    End Sub

    Public Function Read(bytes As Integer) As Byte()
        Dim results() As Byte = FileUtils.ReadFromFile(fileName, bytes)
        If results Is Nothing
            Throw NewFileIOException()
        End If
        Return results
    End Function

    Function NewFileIOException() As FileReaderException
        Dim description As String = &quot;My NewFileIOException Description&quot;

        Return New FileReaderException(description)
    End Function
End Class
</code></pre><p>Alternatively, use the exception&#39;s constructor to build the exception. This is more appropriate for global exception classes such as <a href="https://msdn.microsoft.com/library/system.argumentexception">ArgumentException</a>.</p>
</li>
<li><p>Clean up intermediate results when throwing an exception. Callers should be able to assume that there are no side effects when an exception is thrown from a method.</p>
</li>
</ul>

            </article>
          </div>
          
          <div class="hidden-sm col-md-2" role="complementary">
            <nav class="bs-docs-sidebar hidden-print hidden-xs hidden-sm affix" id="affix">
            <!-- <p><a class="back-to-top" href="#top">Back to top</a><p> -->
            </nav>
          </div>
        </div>
      </div>
      
      <footer>
        <div class="inner-footer">
          <p>© .NET Foundation</p>
          <p>
            <a href="https://www.github.com/dotnet" target="_blank"><span class="fa fa-stack fa-lg">
              <span class="fa fa-square-o fa-stack-2x"></span>
              <span class="fa fa-github fa-stack-1x"></span>
            </span></a>
            <a href="https://twitter.com/dotnet" target="_blank"><span class="fa fa-stack fa-lg">
              <span class="fa fa-square-o fa-stack-2x"></span>
              <span class="fa fa-twitter fa-stack-1x"></span>
            </span></a>
            <a href="https://www.facebook.com/dotnet" target="_blank"><span class="fa fa-stack fa-lg">
              <span class="fa fa-square-o fa-stack-2x"></span>
              <span class="fa fa-facebook fa-stack-1x"></span>
            </span></a>
      
          </p>
          </div>
      </footer>
    </div>
    
    <script type="text/javascript" src="../../../styles/docfx.vendor.js"></script>
    <script type="text/javascript" src="../../../styles/docfx.js"></script>
    <script type="text/javascript" src="../../../styles/main.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
  </body>
</html>
